{
  "openapi": "3.0.2",
  "info": {
    "title": "1Password Connect",
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_thumb_e_e3_1password-logo.svg_1280px-1password-logo.svg.png"
    },
    "contact": {
      "url": "https://support.1password.com/",
      "name": "1Password Integrations",
      "email": "support@1password.com"
    },
    "version": "1.5.7",
    "x-origin": [
      {
        "url": "https://i.1password.com/media/1password-connect/1password-connect-api.yaml",
        "format": "openapi",
        "version": "3.0"
      }
    ],
    "description": "REST API interface for 1Password Connect.",
    "x-serviceName": "connect",
    "x-providerName": "1password.local",
    "x-apisguru-categories": [
      "security"
    ]
  },
  "servers": [
    {
      "url": "http://localhost:8080/v1",
      "description": "Main (production) server"
    },
    {
      "url": "http://1password.local",
      "description": "Internal test server"
    }
  ],
  "paths": {
    "/1password-connect/vaults/{vaultUuid}/items/{itemUuid}/files/{fileUuid}/content": {
      "get": {
        "operationId": "DownloadFileByID",
        "responses": {
          "200": {
            "content": {
              "application/octet-stream": {
                "schema": {
                  "format": "binary",
                  "type": "string"
                }
              }
            },
            "description": "Success",
            "headers": {
              "Content-Disposition": {
                "schema": {
                  "example": "attachment; filename=\"privkey.pem\"",
                  "type": "string"
                }
              },
              "Content-Length": {
                "schema": {
                  "example": "6432",
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "Invalid token signature",
                  "status": 401
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Invalid or missing token"
          },
          "404": {
            "content": {
              "application/json": {
                "examples": {
                  "fileNotFound": {
                    "summary": "File not found",
                    "value": {
                      "message": "file {fileUuid} not found",
                      "status": 404
                    }
                  },
                  "itemNotFound": {
                    "summary": "Item not found",
                    "value": {
                      "message": "item {itemUuid} not found",
                      "status": 404
                    }
                  },
                  "vaultNotFound": {
                    "summary": "Vault not found",
                    "value": {
                      "message": "vault {vaultUuid} not found",
                      "status": 404
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "File not found"
          }
        },
        "summary": "Get the content of a File",
        "tags": [
          "Files"
        ],
        "parameters": [
          {
            "name": "vaultUuid",
            "in": "path",
            "description": "ID of vaultUuid to return",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/1password-connect/vaults/{vaultUuid}/items/{itemUuid}/files/{fileUuid}": {
      "get": {
        "operationId": "GetDetailsOfFileById",
        "parameters": [
          {
            "description": "The UUID of the Vault to fetch Item from",
            "in": "path",
            "name": "vaultUuid",
            "required": true,
            "schema": {
              "format": "uuid",
              "type": "string"
            }
          },
          {
            "description": "The UUID of the Item to fetch File from",
            "in": "path",
            "name": "itemUuid",
            "required": true,
            "schema": {
              "format": "uuid",
              "type": "string"
            }
          },
          {
            "description": "The UUID of the File to fetch",
            "in": "path",
            "name": "fileUuid",
            "required": true,
            "schema": {
              "format": "uuid",
              "type": "string"
            }
          },
          {
            "description": "Tells server to return the base64-encoded file contents in the response.",
            "in": "query",
            "name": "inline_files",
            "schema": {
              "example": true,
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/File"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "Invalid token signature",
                  "status": 401
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Invalid or missing token"
          },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "message": "vault {vaultUuid} is not in scope",
                  "status": 403
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unauthorized access"
          },
          "404": {
            "content": {
              "application/json": {
                "examples": {
                  "fileNotFound": {
                    "summary": "File not found",
                    "value": {
                      "message": "file {fileUuid} not found",
                      "status": 404
                    }
                  },
                  "itemNotFound": {
                    "summary": "Item not found",
                    "value": {
                      "message": "item {itemUuid} not found",
                      "status": 404
                    }
                  },
                  "vaultNotFound": {
                    "summary": "Vault not found",
                    "value": {
                      "message": "vault {vaultUuid} not found",
                      "status": 404
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "File not found"
          },
          "413": {
            "content": {
              "application/json": {
                "examples": {
                  "fileTooLarge": {
                    "summary": "File too large",
                    "value": {
                      "message": "File is too large to inline in request. Use the /v1/vaults/{vaultUUID}/items/{itemUUID}/files/{fileUUID}/content endpoint instead.",
                      "status": 413
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "File content too large to display"
          }
        },
        "summary": "Get the details of a File",
        "tags": [
          "Files"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "File": {
        "type": "object",
        "example": {
          "id": "6r65pjq33banznomn7q22sj44e",
          "name": "foo.txt",
          "size": 35,
          "content": "VGhlIGZ1dHVyZSBiZWxvbmdzIHRvIHRoZSBjdXJpb3VzLgo=",
          "content_path": "v1/vaults/ionaiwtdvgclrixbt6ztpqcxnq/items/p7eflcy7f5mk7vg6zrzf5rjjyu/files/6r65pjq33banznomn7q22sj44e/content"
        },
        "properties": {
          "id": {
            "type": "string",
            "description": "ID of the file"
          },
          "name": {
            "type": "string",
            "description": "Name of the file"
          },
          "size": {
            "type": "integer",
            "description": "Size in bytes of the file"
          },
          "content": {
            "type": "string",
            "format": "byte",
            "description": "Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`."
          },
          "section": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "description": "For files that are in a section, this field describes the section."
          },
          "content_path": {
            "type": "string",
            "readOnly": true,
            "description": "Path of the Connect API that can be used to download the contents of this file."
          }
        }
      },
      "Item": {
        "type": "object",
        "required": [
          "vault",
          "category"
        ],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[\\da-z]{26}$"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "urls": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "href"
              ],
              "properties": {
                "href": {
                  "type": "string",
                  "format": "url"
                },
                "label": {
                  "type": "string"
                },
                "primary": {
                  "type": "boolean"
                }
              }
            },
            "example": [
              {
                "href": "https://example.com",
                "primary": true
              },
              {
                "href": "https://example.org"
              }
            ]
          },
          "state": {
            "enum": [
              "ARCHIVED",
              "DELETED"
            ],
            "type": "string",
            "readOnly": true
          },
          "title": {
            "type": "string"
          },
          "vault": {
            "type": "object",
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "type": "string",
                "pattern": "^[\\da-z]{26}$"
              }
            }
          },
          "version": {
            "type": "integer"
          },
          "category": {
            "enum": [
              "LOGIN",
              "PASSWORD",
              "API_CREDENTIAL",
              "SERVER",
              "DATABASE",
              "CREDIT_CARD",
              "MEMBERSHIP",
              "PASSPORT",
              "SOFTWARE_LICENSE",
              "OUTDOOR_LICENSE",
              "SECURE_NOTE",
              "WIRELESS_ROUTER",
              "BANK_ACCOUNT",
              "DRIVER_LICENSE",
              "IDENTITY",
              "REWARD_PROGRAM",
              "DOCUMENT",
              "EMAIL_ACCOUNT",
              "SOCIAL_SECURITY_NUMBER",
              "MEDICAL_RECORD",
              "SSH_KEY",
              "CUSTOM"
            ],
            "type": "string"
          },
          "favorite": {
            "type": "boolean",
            "default": false
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "lastEditedBy": {
            "type": "string",
            "readOnly": true
          }
        }
      },
      "Field": {
        "type": "object",
        "required": [
          "id",
          "type"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "STRING",
              "EMAIL",
              "CONCEALED",
              "URL",
              "TOTP",
              "DATE",
              "MONTH_YEAR",
              "MENU"
            ],
            "type": "string",
            "default": "STRING"
          },
          "label": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "recipe": {
            "$ref": "#/components/schemas/GeneratorRecipe"
          },
          "entropy": {
            "type": "number",
            "readOnly": true,
            "description": "For fields with a purpose of `PASSWORD` this is the entropy of the value"
          },
          "purpose": {
            "enum": [
              "",
              "USERNAME",
              "PASSWORD",
              "NOTES"
            ],
            "type": "string",
            "description": "Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types."
          },
          "section": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              }
            }
          },
          "generate": {
            "type": "boolean",
            "default": false,
            "description": "If value is not present then a new value should be generated for this field"
          }
        }
      },
      "Patch": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "op",
            "path"
          ],
          "properties": {
            "op": {
              "enum": [
                "add",
                "remove",
                "replace"
              ],
              "type": "string"
            },
            "path": {
              "type": "string",
              "example": "/fields/06gnn2b95example10q91512p5/label",
              "description": "An RFC6901 JSON Pointer pointing to the Item document, an Item Attribute, and Item Field by Field ID, or an Item Field Attribute"
            },
            "value": {
              "type": "object"
            }
          }
        }
      },
      "Vault": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[\\da-z]{26}$"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "enum": [
              "USER_CREATED",
              "PERSONAL",
              "EVERYONE",
              "TRANSFER"
            ],
            "type": "string"
          },
          "items": {
            "type": "integer",
            "description": "Number of active items in the vault"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
          "description": {
            "type": "string"
          },
          "contentVersion": {
            "type": "integer",
            "description": "The version of the vault contents"
          },
          "attributeVersion": {
            "type": "integer",
            "description": "The vault version"
          }
        }
      },
      "FullItem": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Item"
          },
          {
            "type": "object",
            "properties": {
              "files": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/File"
                }
              },
              "fields": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Field"
                }
              },
              "sections": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "APIRequest": {
        "type": "object",
        "properties": {
          "actor": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "jti": {
                "type": "string"
              },
              "account": {
                "type": "string"
              },
              "requestIp": {
                "type": "string"
              },
              "userAgent": {
                "type": "string"
              }
            }
          },
          "action": {
            "enum": [
              "READ",
              "CREATE",
              "UPDATE",
              "DELETE"
            ],
            "type": "string"
          },
          "result": {
            "enum": [
              "SUCCESS",
              "DENY"
            ],
            "type": "string"
          },
          "resource": {
            "type": "object",
            "properties": {
              "item": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[\\da-z]{26}$"
                  }
                }
              },
              "type": {
                "enum": [
                  "ITEM",
                  "VAULT"
                ],
                "type": "string"
              },
              "vault": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[\\da-z]{26}$"
                  }
                }
              },
              "itemVersion": {
                "type": "integer"
              }
            }
          },
          "requestId": {
            "type": "string",
            "format": "uuid",
            "description": "The unique id used to identify a single request."
          },
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "readOnly": true,
            "description": "The time at which the request was processed by the server."
          }
        },
        "description": "Represents a request that was made to the API. Including what Token was used and what resource was accessed."
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP Status Code"
          },
          "message": {
            "type": "string",
            "description": "A message detailing the error"
          }
        }
      },
      "GeneratorRecipe": {
        "type": "object",
        "properties": {
          "length": {
            "type": "integer",
            "default": 32,
            "maximum": 64,
            "minimum": 1,
            "description": "Length of the generated value"
          },
          "characterSets": {
            "type": "array",
            "items": {
              "enum": [
                "LETTERS",
                "DIGITS",
                "SYMBOLS"
              ],
              "type": "string"
            },
            "maximum": 3,
            "minimum": 0,
            "uniqueItems": true
          },
          "excludeCharacters": {
            "type": "string",
            "example": "abc1",
            "description": "List of all characters that should be excluded from generated passwords."
          }
        },
        "description": "The recipe is used in conjunction with the \"generate\" property to set the character set used to generate a new secure value"
      },
      "ServiceDependency": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string",
            "description": "Human-readable message for explaining the current state."
          },
          "service": {
            "type": "string"
          }
        },
        "description": "The state of a registered server dependency."
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "Items",
      "description": "Access and manage items inside 1Password Vaults"
    },
    {
      "name": "Vaults",
      "description": "Access 1Password Vaults"
    },
    {
      "name": "Activity",
      "description": "Access API Request Activity"
    }
  ]
}